import type { CountryPack } from "./types.js";

export const EN_PACK: CountryPack = {
    code: "EN",
    name: "English (Default)",
    currency: {
        code: "USD",
        symbol: "$",
        position: "before",
        decimals: 2,
    },
    locale: "en-US",
    address: {
        regions: [],
        regionLabel: "State / Region",
        postalCodeLabel: "Postal Code",
        phonePrefix: "+1",
        phoneFormat: "(XXX) XXX-XXXX",
    },
    legal: {
        termsLabel: "Terms & Conditions",
        privacyLabel: "Privacy Policy",
        consumerProtectionLabel: "Consumer Protection",
        disputeResolutionLabel: "Dispute Resolution",
    },
    gdpr: {
        headline: "We value your privacy",
        description: "We use cookies to enhance your browsing experience and analyze our traffic. Choose your preference below.",
        denyAll: "Deny All",
        necessaryOnly: "Necessary Only",
        acceptAll: "Accept All",
    },
    defaultStrings: {
        description: "Description",
        addToCart: "Add to Cart",
        addedToCart: "Added to Cart!",
        viewCart: "View Cart",
        inStock: "In Stock",
        outOfStock: "Out of Stock",
        variantUnavailable: "Variant Unavailable",
        units: "units",
        cart: "Cart",
        shoppingCart: "Shopping Cart",
        emptyCart: "Your cart is empty",
        emptyCartMessage: "Browse our products and add something you like.",
        continueShopping: "Continue Shopping",
        orderSummary: "Order Summary",
        subtotal: "Subtotal",
        shipping: "Shipping",
        discount: "Discount",
        total: "Total",
        freeShipping: "Free",
        freeDeliveryFrom: "Free delivery from",
        addMoreForFreeDelivery: "Add {amount} more for free delivery",
        minimumOrder: "Minimum order",
        proceedToCheckout: "Proceed to Checkout",
        couponCode: "Coupon code",
        apply: "Apply",
        remove: "Remove",
        invalidCoupon: "Invalid coupon",
        checkout: "Checkout",
        placeOrder: "Place Order",
        placingOrder: "Placing Order...",
        orderConfirmation: "Order Confirmation",
        contactInformation: "Contact Information",
        fullName: "Full Name",
        email: "Email",
        phone: "Phone",
        phonePlaceholder: "",
        shippingAddress: "Shipping Address",
        streetAddress: "Street Address",
        city: "City",
        county: "County",
        selectCounty: "Select county...",
        postalCode: "Postal Code",
        deliveryNotes: "Delivery Notes",
        deliveryNotesPlaceholder: "Apartment, floor, etc.",
        paymentMethod: "Payment Method",
        cashOnDelivery: "Cash on Delivery",
        cashOnDeliveryDesc: "Pay when you receive your order",
        bankTransfer: "Bank Transfer",
        termsAgreement: "By placing your order, you agree to our terms and conditions.",
        preferredDeliveryDate: "Preferred Delivery Date",
        country: "Country",
        selectCountry: "Select country...",
        birthday: "Birthday",
        birthdayHint: "For a birthday surprise!",
        billingDetails: "Billing Details",
        firstName: "First Name",
        lastName: "Last Name",
        orderAsCompany: "Order as a company",
        companyName: "Company Name",
        taxId: "Tax ID",
        taxIdPlaceholder: "",
        vatNumber: "VAT Number",
        vatNumberPlaceholder: "",
        registrationNumber: "Registration No.",
        registrationNumberPlaceholder: "",
        useSameAsShipping: "Use same address for billing",
        billingAddress: "Billing Address",
        searchButton: "Search",
        searchNoResults: "No products found",
        searchSearching: "Searching...",
        viewAllResults: "View all results",
        resultsFor: "Results for",
        searchProducts: "Search Products",
        signIn: "Sign In",
        accountLabel: "Account",
    },
};
