import type { CountryPack } from "./types.js";

export const RO_PACK: CountryPack = {
    code: "RO",
    name: "Romania",
    currency: {
        code: "RON",
        symbol: "lei",
        position: "after",
        decimals: 2,
    },
    locale: "ro-RO",
    address: {
        regions: [
            { code: "AB", name: "Alba" },
            { code: "AR", name: "Arad" },
            { code: "AG", name: "Arges" },
            { code: "BC", name: "Bacau" },
            { code: "BH", name: "Bihor" },
            { code: "BN", name: "Bistrita-Nasaud" },
            { code: "BT", name: "Botosani" },
            { code: "BV", name: "Brasov" },
            { code: "BR", name: "Braila" },
            { code: "B", name: "Bucuresti" },
            { code: "BZ", name: "Buzau" },
            { code: "CS", name: "Caras-Severin" },
            { code: "CL", name: "Calarasi" },
            { code: "CJ", name: "Cluj" },
            { code: "CT", name: "Constanta" },
            { code: "CV", name: "Covasna" },
            { code: "DB", name: "Dambovita" },
            { code: "DJ", name: "Dolj" },
            { code: "GL", name: "Galati" },
            { code: "GR", name: "Giurgiu" },
            { code: "GJ", name: "Gorj" },
            { code: "HR", name: "Harghita" },
            { code: "HD", name: "Hunedoara" },
            { code: "IL", name: "Ialomita" },
            { code: "IS", name: "Iasi" },
            { code: "IF", name: "Ilfov" },
            { code: "MM", name: "Maramures" },
            { code: "MH", name: "Mehedinti" },
            { code: "MS", name: "Mures" },
            { code: "NT", name: "Neamt" },
            { code: "OT", name: "Olt" },
            { code: "PH", name: "Prahova" },
            { code: "SM", name: "Satu Mare" },
            { code: "SJ", name: "Salaj" },
            { code: "SB", name: "Sibiu" },
            { code: "SV", name: "Suceava" },
            { code: "TR", name: "Teleorman" },
            { code: "TM", name: "Timis" },
            { code: "TL", name: "Tulcea" },
            { code: "VS", name: "Vaslui" },
            { code: "VL", name: "Valcea" },
            { code: "VN", name: "Vrancea" },
        ],
        regionLabel: "Jude\u021B",
        postalCodeLabel: "Cod Po\u0219tal",
        postalCodeFormat: "\\d{6}",
        phonePrefix: "+40",
        phoneFormat: "07XX XXX XXX",
    },
    legal: {
        termsLabel: "Termeni \u0219i condi\u021Bii",
        privacyLabel: "Politica de confiden\u021Bialitate",
        consumerProtectionLabel: "ANPC",
        disputeResolutionLabel: "Solu\u021Bionare alternativ\u0103 a litigiilor",
    },
    defaultStrings: {
        description: "Descriere",
        addToCart: "Adaug\u0103 \u00EEn co\u0219",
        addedToCart: "Ad\u0103ugat \u00EEn co\u0219!",
        viewCart: "Vezi co\u0219ul",
        inStock: "\u00CEn stoc",
        outOfStock: "Stoc epuizat",
        variantUnavailable: "Variant\u0103 indisponibil\u0103",
        units: "unit\u0103\u021Bi",
        cart: "Co\u0219",
        shoppingCart: "Co\u0219 de cump\u0103r\u0103turi",
        emptyCart: "Co\u0219ul t\u0103u este gol",
        emptyCartMessage: "R\u0103sfoie\u0219te produsele noastre \u0219i adaug\u0103 ceva ce \u00EE\u021Bi place.",
        continueShopping: "Continu\u0103 cump\u0103r\u0103turile",
        orderSummary: "Sumar comand\u0103",
        subtotal: "Subtotal",
        shipping: "Livrare",
        discount: "Reducere",
        total: "Total",
        freeShipping: "Gratuit",
        freeDeliveryFrom: "Livrare gratuit\u0103 de la",
        addMoreForFreeDelivery: "Adaug\u0103 \u00EEnc\u0103 {amount} pentru livrare gratuit\u0103",
        minimumOrder: "Comand\u0103 minim\u0103",
        proceedToCheckout: "Finalizeaz\u0103 comanda",
        couponCode: "Cod cupon",
        apply: "Aplic\u0103",
        remove: "\u0218terge",
        invalidCoupon: "Cupon invalid",
        checkout: "Finalizare comand\u0103",
        placeOrder: "Plaseaz\u0103 comanda",
        placingOrder: "Se plaseaz\u0103 comanda...",
        orderConfirmation: "Confirmare comand\u0103",
        contactInformation: "Informa\u021Bii de contact",
        fullName: "Nume complet",
        email: "Email",
        phone: "Telefon",
        phonePlaceholder: "07XX XXX XXX",
        shippingAddress: "Adresa de livrare",
        streetAddress: "Strada",
        city: "Ora\u0219",
        county: "Jude\u021B",
        selectCounty: "Selecteaz\u0103 jude\u021Bul...",
        postalCode: "Cod po\u0219tal",
        deliveryNotes: "Note livrare",
        deliveryNotesPlaceholder: "Apartament, etaj, etc.",
        paymentMethod: "Metod\u0103 de plat\u0103",
        cashOnDelivery: "Plata la livrare (ramburs)",
        cashOnDeliveryDesc: "Pl\u0103te\u0219ti c\u00E2nd prime\u0219ti comanda",
        bankTransfer: "Transfer bancar",
        termsAgreement: "Prin plasarea comenzii, e\u0219ti de acord cu termenii \u0219i condi\u021Biile noastre.",
        preferredDeliveryDate: "Data de livrare preferat\u0103",
        country: "\u021Aar\u0103",
        selectCountry: "Selecteaz\u0103 \u021Bara...",
        birthday: "Data na\u0219terii",
        birthdayHint: "Pentru o surpriz\u0103 de ziua ta!",
        billingDetails: "Date de facturare",
        firstName: "Prenume",
        lastName: "Nume",
        orderAsCompany: "Comand\u0103 ca persoan\u0103 juridic\u0103",
        companyName: "Nume firm\u0103",
        taxId: "CUI",
        taxIdPlaceholder: "ex. 12345678",
        vatNumber: "Nr. TVA",
        vatNumberPlaceholder: "ex. RO12345678",
        registrationNumber: "Nr. Reg. Com.",
        registrationNumberPlaceholder: "ex. J40/1234/2020",
        useSameAsShipping: "Folose\u0219te aceea\u0219i adres\u0103 pentru facturare",
        billingAddress: "Adresa de facturare",
        searchButton: "Caut\u0103",
        searchNoResults: "Nu s-au g\u0103sit produse",
        searchSearching: "Se caut\u0103...",
        viewAllResults: "Vezi toate rezultatele",
        resultsFor: "Rezultate pentru",
        searchProducts: "Caut\u0103 produse",
        signIn: "Autentificare",
        accountLabel: "Contul meu",
    },
};
