import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// 1. Load Environment Variables from the .env file generated by post-deploy
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const envPath = path.resolve(__dirname, '.env');

if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
}

// 2. Validate
const apiUrl = process.env.AMODX_API_URL;
const apiKey = process.env.AMODX_API_KEY;

if (!apiUrl || !apiKey) {
    console.error("❌ Error: Missing configuration.");
    console.error("Please run 'npm run post-deploy' in the project root first to generate the .env file.");
    process.exit(1);
}

// 3. Determine Server Script Path
const serverScriptPath = path.resolve(__dirname, 'dist/index.js');
if (!fs.existsSync(serverScriptPath)) {
    console.error(`❌ Error: Could not find build artifact at: ${serverScriptPath}`);
    console.error("Did you run 'npm run build' in tools/mcp-server?");
    process.exit(1);
}

// 4. Locate Claude Config
let configPath = '';
const platform = os.platform();

if (platform === 'darwin') {
    configPath = path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json');
} else if (platform === 'win32') {
    configPath = path.join(os.homedir(), 'AppData', 'Roaming', 'Claude', 'claude_desktop_config.json');
} else {
    console.error(`Unsupported platform: ${platform}`);
    process.exit(1);
}

console.log(`📍 Targeting Claude Config: ${configPath}`);

// 5. Update the Config
try {
    const configDir = path.dirname(configPath);
    if (!fs.existsSync(configDir)) {
        fs.mkdirSync(configDir, { recursive: true });
    }

    let config: any = {};
    if (fs.existsSync(configPath)) {
        config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    }

    if (!config.mcpServers) config.mcpServers = {};

    // Inject AMODX configuration with ENV VARS baked in
    config.mcpServers['amodx'] = {
        command: 'node',
        args: [serverScriptPath],
        env: {
            AMODX_API_URL: apiUrl,
            AMODX_API_KEY: apiKey,
            PATH: process.env.PATH
        }
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    console.log("✅ Claude Desktop configuration updated successfully.");
    console.log("👉 Please RESTART Claude Desktop for changes to take effect.");

} catch (error: any) {
    console.error("Failed to update config:", error.message);
    process.exit(1);
}
